env = Environment(CCFLAGS="-std=c++17", CPPPATH='/usr/local/Cellar/antlr4-cpp-runtime/4.7.2/include/antlr4-runtime')

ANTLR_FILES = env.Command(
  target=["out/MathParser.cpp", "out/MathLexer.cpp", "out/MathBaseListener.cpp", "out/MathListener.cpp"],
  source="Math.g",
  action = env.Action(
  "java -jar ~/Downloads/antlr-4.7.2-complete.jar -o out -Dlanguage=Cpp Math.g",
  "Generating antlr"))
SOURCE_FILES = ["main.cc"]
env.Program('a.out', SOURCE_FILES+ANTLR_FILES, LIBS='antlr4-runtime')

